"""add page embeddings

Revision ID: 7d45f88c552e
Revises: 12fcd62d6288
Create Date: 2026-06-14 00:37:25.057969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d45f88c552e'
down_revision: Union[str, Sequence[str], None] = '12fcd62d6288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'chunk_index', name='uq_page_embeddings_page_id_chunk_index')
    )
    op.create_index(op.f('ix_page_embeddings_id'), 'page_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_page_embeddings_page_id'), 'page_embeddings', ['page_id'], unique=False)
    op.drop_table('page_tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_tags',
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('page_tags_page_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('page_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id', 'tag_id', name=op.f('page_tags_pkey'))
    )
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey'))
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.drop_index(op.f('ix_page_embeddings_page_id'), table_name='page_embeddings')
    op.drop_index(op.f('ix_page_embeddings_id'), table_name='page_embeddings')
    op.drop_table('page_embeddings')
    # ### end Alembic commands ###
